# Generated by Django 5.1.1 on 2024-09-12 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name_rus', models.CharField(max_length=30, verbose_name='Last name rus')),
                ('first_name_rus', models.CharField(max_length=30, verbose_name='First name rus')),
                ('patronymic_rus', models.CharField(blank=True, max_length=30, null=True, verbose_name='Patronymic rus')),
                ('last_name_bel', models.CharField(max_length=30, verbose_name='Last name bel')),
                ('first_name_bel', models.CharField(max_length=30, verbose_name='First name bel')),
                ('patronymic_bel', models.CharField(blank=True, max_length=30, null=True, verbose_name='Patronymic bel')),
                ('last_name_en', models.CharField(max_length=30, verbose_name='Last name en')),
                ('first_name_en', models.CharField(max_length=30, verbose_name='First name en')),
                ('patronymic_en', models.CharField(blank=True, max_length=30, null=True, verbose_name='Patronymic en')),
                ('date_of_birth', models.DateField(verbose_name='Date of birth')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/cadets/', verbose_name='Photo')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address')),
                ('passport_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Passport number')),
                ('passport_issue_date', models.DateField(blank=True, null=True, verbose_name='Passport issue date')),
                ('passport_validity_period', models.DateField(blank=True, null=True, verbose_name='Passport validity period')),
                ('father_last_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Father last name')),
                ('father_first_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Father first name')),
                ('father_patronymic', models.CharField(blank=True, max_length=30, null=True, verbose_name='Father patronymic')),
                ('father_date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of birth')),
                ('father_place_of_work', models.TextField(blank=True, null=True, verbose_name='Father place of work')),
                ('father_phone_number', models.CharField(blank=True, max_length=30, null=True, verbose_name='Father phone number')),
                ('mother_last_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Father last name')),
                ('mother_first_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Father first name')),
                ('mother_patronymic', models.CharField(blank=True, max_length=30, null=True, verbose_name='Father patronymic')),
                ('mother_date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of birth')),
                ('mother_place_of_work', models.TextField(blank=True, null=True, verbose_name='Father place of work')),
                ('mother_phone_number', models.CharField(blank=True, max_length=30, null=True, verbose_name='Father phone number')),
                ('school_graduated', models.TextField(blank=True, null=True, verbose_name='School graduated')),
                ('school_graduating_date', models.DateField(blank=True, null=True, verbose_name='School graduating date')),
                ('school_average_score', models.FloatField(blank=True, null=True, verbose_name='School average score')),
                ('academy_start_year', models.IntegerField(blank=True, null=True, verbose_name='Academy start year')),
                ('academy_end_year', models.IntegerField(blank=True, null=True, verbose_name='Academy graduating year')),
            ],
            options={
                'verbose_name': 'Курсант',
                'verbose_name_plural': 'Курсанты',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='EncouragementKind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encouragement_kind', models.CharField(max_length=255, verbose_name='Encouragement kind')),
            ],
            options={
                'verbose_name': 'Вид поощрения',
                'verbose_name_plural': 'Виды поощрений',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=255, unique=True, verbose_name='Group name')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='PassportIssueAuthority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport_issue_authority', models.TextField(unique=True, verbose_name='Passport issue authority')),
            ],
            options={
                'verbose_name': 'Орган выдачи паспорта',
                'verbose_name_plural': 'Органы выдачи паспорта',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='PunishmentKind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punishment_kind', models.CharField(max_length=255, verbose_name='Punishment kind')),
            ],
            options={
                'verbose_name': 'Вид взыскания',
                'verbose_name_plural': 'Виды взысканий',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(max_length=20, unique=True, verbose_name='Rank')),
            ],
            options={
                'verbose_name': 'Звание',
                'verbose_name_plural': 'Звания',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speciality_name', models.TextField(unique=True, verbose_name='Speciality')),
            ],
            options={
                'verbose_name': 'Специальность',
                'verbose_name_plural': 'Специальности',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Encouragement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encouragement_date', models.DateField(blank=True, null=True, verbose_name='Encouragement date')),
                ('encouragement_extra_data', models.TextField(blank=True, null=True, verbose_name='Encouragement extra data')),
                ('encouragement_cadet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kis.cadet', verbose_name='Encouragement cadet')),
                ('encouragement_kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kis.encouragementkind', verbose_name='Encouragement kind')),
            ],
            options={
                'verbose_name': 'Поощрение',
                'verbose_name_plural': 'Поощрения',
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='cadet',
            name='passport_issue_authority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kis.passportissueauthority', verbose_name='Passport issue authority'),
        ),
        migrations.CreateModel(
            name='Punishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punishment_start_date', models.DateField(blank=True, null=True, verbose_name='Punishment start date')),
                ('punishment_expiration_date', models.DateField(blank=True, null=True, verbose_name='Punishment expiration date')),
                ('punishment_extra_data', models.TextField(blank=True, null=True, verbose_name='Punishment extra data')),
                ('punishment_cadet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kis.cadet', verbose_name='Punishment cadet')),
                ('punishment_kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kis.encouragementkind', verbose_name='Punishment kind')),
            ],
            options={
                'verbose_name': 'Поощрение',
                'verbose_name_plural': 'Поощрения',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='RankHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_date', models.DateField(blank=True, null=True, verbose_name='Rank date')),
                ('extra_data', models.TextField(blank=True, null=True, verbose_name='`Extra data')),
                ('cadet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kis.cadet', verbose_name='Cadet')),
                ('rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kis.rank', verbose_name='Rank')),
            ],
            options={
                'verbose_name': 'Присвоение звания',
                'verbose_name_plural': 'Присвоение званий',
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='cadet',
            name='speciality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kis.speciality'),
        ),
        migrations.CreateModel(
            name='Subdivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subdivision_name', models.CharField(max_length=255, verbose_name='Subdivision name')),
                ('subdivision_short_name', models.CharField(max_length=30, verbose_name='Subdivision short name')),
                ('parent_subdivision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kis.subdivision', verbose_name='Parent subdivision')),
            ],
            options={
                'verbose_name': 'Подразделение',
                'verbose_name_plural': 'Подразделения',
                'ordering': ('id',),
            },
        ),
    ]
