# Generated by Django 5.1.1 on 2024-09-12 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadet',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of birth'),
        ),
        migrations.AlterField(
            model_name='cadet',
            name='first_name_bel',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='First name bel'),
        ),
        migrations.AlterField(
            model_name='cadet',
            name='first_name_en',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='First name en'),
        ),
        migrations.AlterField(
            model_name='cadet',
            name='last_name_bel',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Last name bel'),
        ),
        migrations.AlterField(
            model_name='cadet',
            name='last_name_en',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Last name en'),
        ),
    ]
