# Generated by Django 5.1.1 on 2024-09-12 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kis', '0002_alter_cadet_date_of_birth_alter_cadet_first_name_bel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadet',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kis.group'),
        ),
    ]
