# Generated by Django 5.1.1 on 2024-09-17 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kis', '0003_cadet_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadet',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/cadets/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='punishment',
            name='punishment_kind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kis.punishmentkind', verbose_name='Punishment kind'),
        ),
        migrations.AlterField(
            model_name='rankhistory',
            name='extra_data',
            field=models.TextField(blank=True, null=True, verbose_name='Extra data'),
        ),
    ]
