# Generated by Django 5.0.4 on 2024-10-08 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kis', '0004_alter_cadet_photo_alter_punishment_punishment_kind_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='punishment',
            options={'ordering': ('id',), 'verbose_name': 'Взыскание', 'verbose_name_plural': 'Взыскания'},
        ),
    ]
