# Generated by Django 5.0.4 on 2024-10-10 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kis', '0007_componentorgan_countryregion_education_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadet',
            name='school_average_score',
        ),
        migrations.RemoveField(
            model_name='cadet',
            name='school_graduated',
        ),
        migrations.RemoveField(
            model_name='cadet',
            name='school_graduating_year',
        ),
        migrations.RemoveField(
            model_name='cadet',
            name='school_kind',
        ),
        migrations.RemoveField(
            model_name='cadet',
            name='speciality',
        ),
        migrations.AddField(
            model_name='cadet',
            name='arrived_from_go_rovd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kis.go_rovd', verbose_name='Прибыл из ГО-РОВД'),
        ),
        migrations.AddField(
            model_name='cadet',
            name='component_organ',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kis.componentorgan', verbose_name='Комплектующий орган'),
        ),
        migrations.AddField(
            model_name='cadet',
            name='education_average_score',
            field=models.FloatField(blank=True, null=True, verbose_name='Среднее образования (средний бал)'),
        ),
        migrations.AddField(
            model_name='cadet',
            name='education_graduated',
            field=models.TextField(blank=True, null=True, verbose_name='Среднее образования (наименование)'),
        ),
        migrations.AddField(
            model_name='cadet',
            name='education_graduating_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Среднее образования (год)'),
        ),
        migrations.AddField(
            model_name='cadet',
            name='education_kind',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kis.education', verbose_name='Среднее образования (вид учреждения образования)'),
        ),
        migrations.AddField(
            model_name='cadet',
            name='education_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kis.educationlevel', verbose_name='Среднее образования (уровень образования)'),
        ),
        migrations.AddField(
            model_name='cadet',
            name='education_location_kind',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kis.educationlocalitykind', verbose_name='Среднее образования (вид населенного пункта)'),
        ),
        migrations.AddField(
            model_name='cadet',
            name='entrance_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kis.entrancecategory', verbose_name='Категория поступающего'),
        ),
        migrations.AddField(
            model_name='cadet',
            name='extra_data',
            field=models.TextField(blank=True, null=True, verbose_name='Дополнительные данные'),
        ),
        migrations.AddField(
            model_name='cadet',
            name='military_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kis.militaryoffice', verbose_name='Военкомат'),
        ),
        migrations.AddField(
            model_name='cadet',
            name='region_for_medical_examination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kis.countryregion', verbose_name='Область (для прохождения мед. комиссии)'),
        ),
        migrations.AddField(
            model_name='cadet',
            name='social_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kis.socialstatus', verbose_name='Социальный статус'),
        ),
        migrations.AlterField(
            model_name='cadet',
            name='academy_end_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Год окончания'),
        ),
        migrations.AlterField(
            model_name='cadet',
            name='academy_start_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Год поступления'),
        ),
        migrations.AlterField(
            model_name='cadet',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='cadet',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='cadet',
            name='father_date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Отец - дата рождения'),
        ),
        migrations.AlterField(
            model_name='cadet',
            name='father_first_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Отец - имя'),
        ),
        migrations.AlterField(
            model_name='cadet',
            name='father_last_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Отец - фамилия'),
        ),
        migrations.AlterField(
            model_name='cadet',
            name='father_patronymic',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Отец - отчество'),
        ),
        migrations.AlterField(
            model_name='cadet',
            name='father_phone_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Отец - номер телефона'),
        ),
        migrations.AlterField(
            model_name='cadet',
            name='father_place_of_work',
            field=models.TextField(blank=True, null=True, verbose_name='Отец - место работы'),
        ),
        migrations.AlterField(
            model_name='cadet',
            name='first_name_bel',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Имя (бел)'),
        ),
        migrations.AlterField(
            model_name='cadet',
            name='first_name_en',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Имя (англ)'),
        ),
        migrations.AlterField(
            model_name='cadet',
            name='first_name_rus',
            field=models.CharField(max_length=30, verbose_name='Имя (рус)'),
        ),
        migrations.AlterField(
            model_name='cadet',
            name='last_name_bel',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Фамилия (бел)'),
        ),
        migrations.AlterField(
            model_name='cadet',
            name='last_name_en',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Фамилия (англ)'),
        ),
        migrations.AlterField(
            model_name='cadet',
            name='last_name_rus',
            field=models.CharField(max_length=30, verbose_name='Фамилия (рус)'),
        ),
        migrations.AlterField(
            model_name='cadet',
            name='mother_date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Мать - дата рождения'),
        ),
        migrations.AlterField(
            model_name='cadet',
            name='mother_first_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Мать - имя'),
        ),
        migrations.AlterField(
            model_name='cadet',
            name='mother_last_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Мать - фамилия'),
        ),
        migrations.AlterField(
            model_name='cadet',
            name='mother_patronymic',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Мать - отчество'),
        ),
        migrations.AlterField(
            model_name='cadet',
            name='mother_phone_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Мать - номер телефона'),
        ),
        migrations.AlterField(
            model_name='cadet',
            name='mother_place_of_work',
            field=models.TextField(blank=True, null=True, verbose_name='Мать - место работы'),
        ),
        migrations.AlterField(
            model_name='cadet',
            name='passport_issue_authority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kis.passportissueauthority', verbose_name='Орган выдачи паспорта'),
        ),
        migrations.AlterField(
            model_name='cadet',
            name='passport_issue_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выдачи паспорта'),
        ),
        migrations.AlterField(
            model_name='cadet',
            name='passport_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер паспорта'),
        ),
        migrations.AlterField(
            model_name='cadet',
            name='passport_validity_period',
            field=models.DateField(blank=True, null=True, verbose_name='Срок окончания действия паспорта'),
        ),
        migrations.AlterField(
            model_name='cadet',
            name='patronymic_bel',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Отчество (бел)'),
        ),
        migrations.AlterField(
            model_name='cadet',
            name='patronymic_en',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Отчество (англ)'),
        ),
        migrations.AlterField(
            model_name='cadet',
            name='patronymic_rus',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Отчество (рус)'),
        ),
        migrations.AlterField(
            model_name='cadet',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='cadet',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/cadets/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='cadet',
            name='subdivision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kis.subdivision', verbose_name='Подразделение'),
        ),
    ]
