# Generated by Django 5.0.4 on 2024-10-10 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kis', '0009_position_remove_rankhistory_extra_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CadetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория (для курсанта)',
                'verbose_name_plural': 'Категории (для курсанта)',
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='cadet',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kis.cadetcategory', verbose_name='Категория'),
        ),
    ]
