# Generated by Django 5.0.4 on 2024-10-10 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kis', '0010_cadetcategory_cadet_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rank',
            name='rank',
            field=models.CharField(max_length=255, unique=True, verbose_name='Звание'),
        ),
    ]
