# Generated by Django 5.0.4 on 2024-10-15 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kis', '0011_alter_rank_rank'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraduateWithHonorsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255, verbose_name='Вид отличия')),
            ],
            options={
                'verbose_name': 'Вид отличий при окончании УО',
                'verbose_name_plural': 'Виды отличий при окончании УО',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='VPKCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255, verbose_name='Вид ВПК')),
            ],
            options={
                'verbose_name': 'Вид ВПК',
                'verbose_name_plural': 'Виды ВПК',
                'ordering': ('id',),
            },
        ),
        migrations.AlterModelOptions(
            name='positionhistory',
            options={'ordering': ('id',), 'verbose_name': 'Назначение на должность', 'verbose_name_plural': 'Назначения на должность'},
        ),
        migrations.AlterModelOptions(
            name='rankhistory',
            options={'ordering': ('rank_date',), 'verbose_name': 'Присвоение звания', 'verbose_name_plural': 'Присвоение званий'},
        ),
        migrations.AlterModelOptions(
            name='specialityhistory',
            options={'ordering': ('id',), 'verbose_name': 'Перевод на специальность', 'verbose_name_plural': 'Переводы на специальности'},
        ),
        migrations.RemoveField(
            model_name='cadet',
            name='address',
        ),
        migrations.AddField(
            model_name='cadet',
            name='address_registration',
            field=models.TextField(blank=True, null=True, verbose_name='Место жительства (регистрация)'),
        ),
        migrations.AddField(
            model_name='cadet',
            name='address_residence',
            field=models.TextField(blank=True, null=True, verbose_name='Место жительства (проживания)'),
        ),
        migrations.AddField(
            model_name='cadet',
            name='has_achievements_in_sports',
            field=models.BooleanField(default=False, verbose_name='Достижения в спорте'),
        ),
        migrations.AddField(
            model_name='cadet',
            name='identification_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Идентификационный номер'),
        ),
        migrations.AddField(
            model_name='cadet',
            name='is_class_other',
            field=models.BooleanField(default=False, verbose_name='Класс иной направленности'),
        ),
        migrations.AddField(
            model_name='cadet',
            name='is_class_pn',
            field=models.BooleanField(default=False, verbose_name='Класс правовой направленности'),
        ),
        migrations.AddField(
            model_name='cadet',
            name='is_class_vpn',
            field=models.BooleanField(default=False, verbose_name='Класс военно-патриотической направленности'),
        ),
        migrations.AddField(
            model_name='cadet',
            name='is_olympiad_winner',
            field=models.BooleanField(default=False, verbose_name='Победитель республиканских или регионалоных олимпиад'),
        ),
        migrations.AddField(
            model_name='cadet',
            name='place_of_birth',
            field=models.TextField(blank=True, null=True, verbose_name='Место рождения'),
        ),
        migrations.AddField(
            model_name='cadet',
            name='vpk_data',
            field=models.TextField(blank=True, null=True, verbose_name='Данные о ВПК'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='rank',
            field=models.CharField(max_length=20, unique=True, verbose_name='Звание'),
        ),
        migrations.AlterField(
            model_name='rankhistory',
            name='rank_extra_data',
            field=models.TextField(blank=True, null=True, verbose_name='Фабула'),
        ),
        migrations.AddField(
            model_name='cadet',
            name='aims_to_graduate_with_honors',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kis.graduatewithhonorscategory', verbose_name='Претендует на диплом с отличием'),
        ),
        migrations.AddField(
            model_name='cadet',
            name='vpk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kis.vpkcategory', verbose_name='Военно-патриотический класс'),
        ),
    ]
