# Generated by Django 5.0.4 on 2024-10-15 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kis', '0013_ppflcategory_cadet_has_certificate_ideas_for_belarus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForeignLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foreign_language', models.CharField(max_length=255, verbose_name='Иностранный язык')),
            ],
            options={
                'verbose_name': 'Иностранный язык',
                'verbose_name_plural': 'Иностранные языки',
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='cadet',
            name='passed_medical_examination',
            field=models.BooleanField(default=False, verbose_name='Прошел медицинскую комиссию'),
        ),
        migrations.AddField(
            model_name='cadet',
            name='passed_medical_examination_extra_data',
            field=models.TextField(blank=True, null=True, verbose_name='Медицинская комиссия (доп. данные)'),
        ),
        migrations.AddField(
            model_name='cadet',
            name='foreign_language_was',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kis.foreignlanguage', verbose_name='Иностранный язык (изучаемый в школе)'),
        ),
        migrations.AddField(
            model_name='cadet',
            name='foreign_language_will_be',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='foreign_language_will_be', to='kis.foreignlanguage', verbose_name='Иностранный язык (изучаемый в школе)'),
        ),
    ]
