# Generated by Django 5.0.4 on 2024-10-16 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kis', '0014_foreignlanguage_cadet_passed_medical_examination_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_title', models.TextField(blank=True, null=True, verbose_name='Название награды')),
            ],
            options={
                'verbose_name': 'Награда',
                'verbose_name_plural': 'Награды',
                'ordering': ('id',),
            },
        ),
        migrations.RemoveField(
            model_name='cadet',
            name='education_average_score',
        ),
        migrations.RemoveField(
            model_name='cadet',
            name='education_graduated',
        ),
        migrations.RemoveField(
            model_name='cadet',
            name='education_graduating_year',
        ),
        migrations.RemoveField(
            model_name='cadet',
            name='education_kind',
        ),
        migrations.RemoveField(
            model_name='cadet',
            name='education_level',
        ),
        migrations.RemoveField(
            model_name='cadet',
            name='education_location_kind',
        ),
        migrations.RemoveField(
            model_name='cadet',
            name='military_service_end',
        ),
        migrations.RemoveField(
            model_name='cadet',
            name='military_service_start',
        ),
        migrations.RemoveField(
            model_name='cadet',
            name='mvd_service_end',
        ),
        migrations.RemoveField(
            model_name='cadet',
            name='mvd_service_start',
        ),
        migrations.AddField(
            model_name='cadet',
            name='personal_number_mvd',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Личный номер'),
        ),
        migrations.CreateModel(
            name='ArmyService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('military_service_start', models.DateField(blank=True, null=True, verbose_name='Служба в армии (начало)')),
                ('military_service_end', models.DateField(blank=True, null=True, verbose_name='Служба в армии (окончание)')),
                ('position', models.TextField(blank=True, null=True, verbose_name='Должность (без сокращений)')),
                ('order_date', models.DateField(blank=True, null=True, verbose_name='Дата приказа')),
                ('order_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер приказа')),
                ('cadet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kis.cadet', verbose_name='Курсант')),
                ('order_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kis.orderowner', verbose_name='Чей приказ')),
            ],
            options={
                'verbose_name': 'Служба в армии',
                'verbose_name_plural': 'Службы в армии',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='EducationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_graduated', models.TextField(blank=True, null=True, verbose_name='Наименование учебного заведения')),
                ('education_graduating_start_year', models.IntegerField(blank=True, null=True, verbose_name='Год поступления')),
                ('education_graduating_end_year', models.IntegerField(blank=True, null=True, verbose_name='Год окончания')),
                ('education_average_score', models.FloatField(blank=True, null=True, verbose_name='Средний бал')),
                ('cadet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kis.cadet', verbose_name='Курсант')),
                ('education_kind', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kis.education', verbose_name='Вид учреждения образования')),
                ('education_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kis.educationlevel', verbose_name='Уровень образования')),
                ('education_location_kind', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kis.educationlocalitykind', verbose_name='Вид населенного пункта')),
            ],
            options={
                'verbose_name': 'Образование',
                'verbose_name_plural': 'Образования',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='JobHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_position', models.TextField(blank=True, null=True, verbose_name='Должность')),
                ('job_start_year', models.IntegerField(blank=True, null=True, verbose_name='Год начала работы')),
                ('job_end_year', models.IntegerField(blank=True, null=True, verbose_name='Год увольнения работы')),
                ('organisation_name', models.TextField(blank=True, null=True, verbose_name='Организация, где работал')),
                ('cadet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kis.cadet', verbose_name='Курсант')),
            ],
            options={
                'verbose_name': 'Работа',
                'verbose_name_plural': 'Работы',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='MVDService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mvd_service_start', models.DateField(blank=True, null=True, verbose_name='Служба в армии (начало)')),
                ('mvd_military_service_end', models.DateField(blank=True, null=True, verbose_name='Служба в армии (окончание)')),
                ('position', models.TextField(blank=True, null=True, verbose_name='Должность (без сокращений)')),
                ('order_date', models.DateField(blank=True, null=True, verbose_name='Дата приказа')),
                ('order_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер приказа')),
                ('cadet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kis.cadet', verbose_name='Курсант')),
                ('order_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kis.orderowner', verbose_name='Чей приказ')),
            ],
            options={
                'verbose_name': 'Служба в МВД',
                'verbose_name_plural': 'Службы в МВД',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='RewardHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_date', models.DateField(blank=True, null=True, verbose_name='Дата награды')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='За что награжден')),
                ('order_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер приказа')),
                ('cadet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kis.cadet', verbose_name='Курсант')),
                ('order_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kis.orderowner', verbose_name='Чей приказ')),
            ],
            options={
                'verbose_name': 'Награда присвоение',
                'verbose_name_plural': 'Награда присвоения',
                'ordering': ('id',),
            },
        ),
    ]
