# Generated by Django 5.0.4 on 2024-10-16 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kis', '0015_reward_remove_cadet_education_average_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewardhistory',
            name='reward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kis.reward', verbose_name='Награда'),
        ),
    ]
