# Generated by Django 5.0.4 on 2024-10-16 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kis', '0016_rewardhistory_reward'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mvdservice',
            old_name='mvd_military_service_end',
            new_name='mvd_service_end',
        ),
    ]
