# Generated by Django 5.0.4 on 2024-10-16 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kis', '0018_rename_encouragement_cadet_encouragement_cadet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='armyservice',
            name='military_organization',
            field=models.TextField(blank=True, null=True, verbose_name='Место службы'),
        ),
        migrations.AddField(
            model_name='mvdservice',
            name='mvd_organization',
            field=models.TextField(blank=True, null=True, verbose_name='Место службы'),
        ),
    ]
