# Generated by Django 5.0.4 on 2024-10-17 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kis', '0019_armyservice_military_organization_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaritalStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marital_status', models.CharField(max_length=255, verbose_name='Семейное положение')),
            ],
            options={
                'verbose_name': 'Семейное положение',
                'verbose_name_plural': 'Семейные положения',
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='cadet',
            name='marital_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kis.maritalstatus', verbose_name='Семейное положение'),
        ),
    ]
