# Generated by Django 5.0.4 on 2024-10-18 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kis', '0020_maritalstatus_cadet_marital_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cadet',
            options={'ordering': ('-id',), 'verbose_name': 'Курсант', 'verbose_name_plural': 'Курсанты'},
        ),
        migrations.AlterField(
            model_name='cadet',
            name='first_name_rus',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Имя (рус)'),
        ),
        migrations.AlterField(
            model_name='cadet',
            name='last_name_rus',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Фамилия (рус)'),
        ),
    ]
