# Generated by Django 5.0.4 on 2024-10-08 07:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_method', models.CharField(blank=True, max_length=10, null=True, verbose_name='Request method')),
                ('request_body', models.TextField(blank=True, null=True, verbose_name='Request body')),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='Date time')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log',
                'verbose_name_plural': 'Logs',
                'ordering': ('id',),
            },
        ),
    ]
