# Generated by Django 5.0.4 on 2024-10-08 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applogging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logdata',
            name='request_path',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Request path'),
        ),
    ]
