from django.contrib import admin
from kis.models import (CadetCategory, Cadet, Rank, PassportIssueAuthority, Speciality, Subdivision,
                        Punishment, PunishmentKind, EncouragementKind, Encouragement, RankHistory, ComponentOrgan,
                        EntranceCategory, GO_ROVD, SocialStatus, CountryRegion, MilitaryOffice, Education,
                        EducationLevel, EducationLocalityKind, OrderOwner, Position, PositionHistory, SpecialityHistory,
                        EducationHistory, MVDService, ArmyService, JobHistory, Reward, RewardHistory, Group)

admin.site.register(CadetCategory)
admin.site.register(Cadet)
admin.site.register(Rank)
admin.site.register(PassportIssueAuthority)
admin.site.register(Speciality)
admin.site.register(Subdivision)
admin.site.register(Punishment)
admin.site.register(PunishmentKind)
admin.site.register(EncouragementKind)
admin.site.register(Encouragement)
admin.site.register(RankHistory)
admin.site.register(ComponentOrgan)
admin.site.register(EntranceCategory)
admin.site.register(GO_ROVD)
admin.site.register(SocialStatus)
admin.site.register(CountryRegion)
admin.site.register(MilitaryOffice)
admin.site.register(Education)
admin.site.register(EducationLevel)
admin.site.register(EducationLocalityKind)
admin.site.register(Position)
admin.site.register(OrderOwner)
admin.site.register(PositionHistory)
admin.site.register(SpecialityHistory)
admin.site.register(EducationHistory)
admin.site.register(MVDService)
admin.site.register(ArmyService)
admin.site.register(JobHistory)
admin.site.register(Reward)
admin.site.register(RewardHistory)
admin.site.register(Group)
